## Importación de librería y datos

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
import seaborn as sns

In [2]:
ruta_docentes = (
    Path("..") / ".." / "Recursos"
    / "Dataset docentes concatenado"
    / "dataset_docentes_consolidado.parquet"
)
print(ruta_docentes.exists())
df_d = pd.read_parquet(ruta_docentes)
print(df_d.shape)

True
(379153, 14)

In [3]:
ruta_estudiantes = (
    Path("..") / ".." / "Recursos"
    / "Dataset estudiantes concatenado"
    / "dataset_estudiantes_consolidado.parquet"
)
print(ruta_estudiantes.exists())
df_e = pd.read_parquet(ruta_estudiantes)
print(df_e.shape)

True
(4560711, 21)

In [4]:
for i, col in enumerate(df_e.columns, start=1):
    print(f"{i}. {col}")

1. Id persona
2. Sexo
3. Rol
4. Departamento
5. Subsistema
6. Ciclo
7. Grado
8. Zona
9. Contexto
10. Año lectivo
11. Cantidad de días ingreso a CREA
12. Cantidad de entregas de tareas
13. Cantidad de Comentarios posteados
14. Cantidad de Acciones totales
15. Cantidad de días de ingreso a Matific
16. Cantidad de episodios finalizados en Matific
17. Cantidad de días de ingreso a PAM
18. Cantidad de actividades finalizadas en PAM
19. Cantidad de días de ingreso a Biblioteca
20. Cantidad de préstamos en biblioteca
21. archivo_origen

In [5]:
df_d["comentarios"] = df_d["Cantidad de Comentarios posteados"].combine_first(
    df_d["Cantidad de Comentarios posteados en CREA"]
)
df_d["acciones"] = df_d["Cantidad de Acciones totales"].combine_first(
    df_d["Cantidad de Acciones totales en CREA"]
)
df_d = df_d.drop(columns=[
    "Cantidad de Comentarios posteados", "Cantidad de Comentarios posteados en CREA",
    "Cantidad de Acciones totales", "Cantidad de Acciones totales en CREA",
])

### **Comprobación de los años que contiene cada archivo**

**Motivo.** Al revisar el catálogo de datos abiertos de Ceibal encontré dos inconsistencias de documentación en el dataset de estudiantes. Comprobé si el contenido de cada archivo coincide con el año que indica su nombre.

**Observaciones en la ficha del catálogo** (consultada el 12/10/2026):
1. La descripción del recurso "Actividad de estudiantes - 2024" dice "Corresponden a los datos de actividad del estudiante del año 2022", aunque su título y el nombre del archivo indican 2024. https://catalogodatos.gub.uy/dataset/centro_ceibal-actividad-en-plataformas-educativas-estudiantes/resource/b156c9bd-40dc-4b15-a952-bac8625ad6b3
2. El recurso "Actividad de estudiantes - 2023" se descarga como `estudiantes_datos_abiertos_agesic.csv`, sin año en el nombre y fuera de la nomenclatura de los demás archivos. https://catalogodatos.gub.uy/dataset/centro_ceibal-actividad-en-plataformas-educativas-estudiantes/resource/4d9ab478-cd34-4cbb-bbaa-61144e74dde1

**Comprobación en los datos.** Agrupé por `archivo_origen` y listé los valores de `Año lectivo`.

**Resultado.** Cada archivo, de estudiantes y de docentes, contiene un único año, igual al de su nombre. El archivo de 2024 contiene solo 2024 y el de 2023, solo 2023.

**Conclusión.** El contenido de los archivos es coherente con el año de su nombre; las inconsistencias están en la documentación del catálogo. Se desconoce la causa (por ejemplo, un error de redacción en la ficha): queda como consulta pendiente para Ceibal.

In [6]:
# Comprobación de archivos - Docentes
df_d.groupby("archivo_origen")["Año lectivo"].unique()

archivo_origen
actividad-de-docentes-2024.csv        [2024]
actividad-de-docentes-2025.csv        [2025]
datos_docentes_2019.csv               [2019]
datos_docentes_2020.csv               [2020]
datos_docentes_2021.csv               [2021]
datos_docentes_2022.csv               [2022]
docentes_datos_abiertos_agesic.csv    [2023]
Name: Año lectivo, dtype: object

In [7]:
# Comprobación de archivos - Estudiantes
df_e.groupby("archivo_origen")["Año lectivo"].unique()

archivo_origen
actividad-de-estudiantes-2024.csv        [2024]
actividad-de-estudiantes-2025.csv        [2025]
datos_estudiantes_2019.csv               [2019]
datos_estudiantes_2020.csv               [2020]
datos_estudiantes_2021.csv               [2021]
datos_estudiantes_2022.csv               [2022]
estudiantes_datos_abiertos_agesic.csv    [2023]
Name: Año lectivo, dtype: object

## Exploración de los datos - DataFrame Docente

In [8]:
# Listado de columnas en el DF de docentes (df_d)
for i, col in enumerate(df_d.columns, start=1):
    print(f"{i}. {col}")

1. Id persona
2. Sexo
3. Rol
4. Departamento
5. Subsistema
6. Año lectivo
7. Cantidad de días ingreso a CREA
8. Cantidad de días de ingreso a Biblioteca
9. Cantidad de préstamos en biblioteca
10. archivo_origen
11. comentarios
12. acciones

In [9]:
df_d["Sexo"].value_counts()

Sexo
Femenino      243968
Masculino      78631
Femenino       42469
Masculino      13605
Sin Dato         480
Name: count, dtype: int64

In [10]:
df_d.head()

,Id persona,Sexo,Rol,Departamento,Subsistema,Año lectivo,Cantidad de días ingreso a CREA,Cantidad de días de ingreso a Biblioteca,Cantidad de préstamos en biblioteca,archivo_origen,comentarios,acciones
0,702122,Femenino,Docente,Montevideo,DGES,2024,0,0,0,actividad-de-docentes-2024.csv,0.0,0.0
1,199850,Masculino,Docente,Montevideo,DGETP,2024,0,0,0,actividad-de-docentes-2024.csv,0.0,0.0
2,1686169,Masculino,Docente,Salto,DGES,2024,0,0,0,actividad-de-docentes-2024.csv,0.0,0.0
3,1680863,Masculino,Docente,Montevideo,DGEIP,2024,0,0,0,actividad-de-docentes-2024.csv,0.0,0.0
4,1802728,Femenino,Docente,Paysandu,DGES,2024,0,0,0,actividad-de-docentes-2024.csv,0.0,0.0

#### Normalización de valores y limpieza de duplicados

In [11]:
pd.crosstab(df_d["archivo_origen"], df_d["Sexo"].map(repr))

Sexo,'Femenino ','Femenino','Masculino ','Masculino','Sin Dato'
archivo_origen,,,,,
actividad-de-docentes-2024.csv,0,41822,0,13342,1
actividad-de-docentes-2025.csv,42469,0,13605,0,0
datos_docentes_2019.csv,0,38806,0,12112,452
datos_docentes_2020.csv,0,38053,0,12066,3
datos_docentes_2021.csv,0,39787,0,12606,0
datos_docentes_2022.csv,0,41294,0,13188,13
docentes_datos_abiertos_agesic.csv,0,44206,0,15317,11

In [12]:
# Tenemos que limpiar los strings de la columna "Sexo"
# Al escribir el dataset probablemente hubo un error de exportación y de esa manera aparece (" ") al final de la palabra
# Para Python, estos son dos cosas distintas. Así que debemos limpiarlas

df_d["Sexo"] = df_d["Sexo"].str.strip()
df_d["Sexo"].value_counts()

Sexo
Femenino     286437
Masculino     92236
Sin Dato        480
Name: count, dtype: int64

In [13]:
pd.crosstab(df_d["archivo_origen"], df_d["Subsistema"].map(repr))

Subsistema,'DGEIP ','DGEIP','DGES ','DGES','DGETP ','DGETP'
archivo_origen,,,,,,
actividad-de-docentes-2024.csv,0,20203,0,20931,0,14031
actividad-de-docentes-2025.csv,20380,0,21180,0,14514,0
datos_docentes_2019.csv,0,18968,0,20239,0,12163
datos_docentes_2020.csv,0,18050,0,19644,0,12428
datos_docentes_2021.csv,0,20002,0,19561,0,12830
datos_docentes_2022.csv,0,20125,0,21205,0,13165
docentes_datos_abiertos_agesic.csv,0,19954,0,26214,0,13366

In [14]:
# Al igual que antes, debemos limpiar los espacios en blanco de la columna "Subsistema"

df_d["Subsistema"] = df_d["Subsistema"].str.strip()
df_d["Subsistema"].value_counts()

Subsistema
DGES     148974
DGEIP    137682
DGETP     92497
Name: count, dtype: int64

In [15]:
pd.crosstab(df_d["archivo_origen"], df_d["Departamento"].map(repr))

Departamento,'Artigas ','Artigas','Canelones ','Canelones','Cerro Largo ','Cerro Largo','Colonia ','Colonia','Durazno ','Durazno',...,'San Jose ','San Jose','Sin Dato ','Sin Dato','Soriano ','Soriano','Tacuarembo ','Tacuarembo','Treinta Y Tres ','Treinta Y Tres'
archivo_origen,,,,,,,,,,,,,,,,,,,,,
actividad-de-docentes-2024.csv,0,1706,0,8966,0,1886,0,2554,0,1178,...,0,2025,0,31,0,1659,0,1962,0,1016
actividad-de-docentes-2025.csv,1801,0,9271,0,1853,0,2583,0,1161,0,...,2042,0,8,0,1679,0,1946,0,1031,0
datos_docentes_2019.csv,0,1614,0,8109,0,1736,0,2387,0,1145,...,0,1800,0,0,0,1747,0,1948,0,1049
datos_docentes_2020.csv,0,1570,0,8096,0,1717,0,2325,0,1112,...,0,1742,0,0,0,1663,0,1854,0,964
datos_docentes_2021.csv,0,1637,0,8482,0,1819,0,2438,0,1137,...,0,1855,0,0,0,1678,0,1939,0,983
datos_docentes_2022.csv,0,1684,0,9132,0,1782,0,2520,0,1132,...,0,1956,0,0,0,1690,0,1906,0,1008
docentes_datos_abiertos_agesic.csv,0,1963,0,9544,0,1842,0,2999,0,1365,...,0,2380,0,0,0,2019,0,2058,0,1118

In [16]:
# Al igual que antes, debemos limpiar los espacios en blanco de la columna "Departamento"

df_d["Departamento"] = df_d["Departamento"].str.strip()
df_d["Departamento"].value_counts()

Departamento
Montevideo        109581
Canelones          61600
Maldonado          20495
Salto              17980
Colonia            17806
Rivera             16286
Paysandu           16201
San Jose           13800
Tacuarembo         13613
Cerro Largo        12635
Soriano            12135
Artigas            11975
Rocha              10524
Florida             9781
Rio Negro           8279
Durazno             8230
Lavalleja           7536
Treinta Y Tres      7169
Flores              3488
Sin Dato              39
Name: count, dtype: int64

In [17]:
# Vamos a ver la cantidad de ID's duplicados
# Hay que tener en cuenta que se repiten, a veces, porque son ID de docentes 
# que pueden estar en distintos subsistemas en un mismo año.
df_d["Id persona"].nunique(), len(df_d)

(74929, 379153)

In [18]:
df_d.duplicated(subset=["Id persona", "Año lectivo"]).sum()

np.int64(39031)

In [19]:
df_d["Id persona"].value_counts().value_counts().sort_index()

count
1     16041
2      6022
3      5320
4      5341
5      4929
6      4947
7     24093
8      2027
9       991
10      820
11      649
12      690
13      837
14     2211
15        6
16        2
17        1
18        1
20        1
Name: count, dtype: Int64

In [20]:
dup = df_d[df_d.duplicated(subset=["Id persona", "Año lectivo"], keep=False)] # Variable para verificar duplicados por "id" y "año lectivo"

# Vamos a ver un ejemplo de un id repetido
id_ejemplo = dup["Id persona"].iloc[0]
df_d[df_d["Id persona"] == id_ejemplo].sort_values("Año lectivo")

,Id persona,Sexo,Rol,Departamento,Subsistema,Año lectivo,Cantidad de días ingreso a CREA,Cantidad de días de ingreso a Biblioteca,Cantidad de préstamos en biblioteca,archivo_origen,comentarios,acciones
120798,199850,Masculino,Docente,Montevideo,DGETP,2019,106,0,0,datos_docentes_2019.csv,10.0,825.0
171560,199850,Masculino,Docente,Montevideo,DGETP,2020,92,0,0,datos_docentes_2020.csv,11.0,959.0
222385,199850,Masculino,Docente,Montevideo,DGETP,2021,55,1,0,datos_docentes_2021.csv,13.0,175.0
329948,199850,Masculino,Docente,Montevideo,DGETP,2023,33,1,1,docentes_datos_abiertos_agesic.csv,8.0,138.0
329949,199850,Masculino,Docente,Montevideo,DGES,2023,33,1,1,docentes_datos_abiertos_agesic.csv,8.0,138.0
1,199850,Masculino,Docente,Montevideo,DGETP,2024,0,0,0,actividad-de-docentes-2024.csv,0.0,0.0
2284,199850,Masculino,Docente,Montevideo,DGETP,2024,136,2,0,actividad-de-docentes-2024.csv,24.0,1478.0

In [21]:
dup["archivo_origen"].value_counts()

archivo_origen
docentes_datos_abiertos_agesic.csv    12607
actividad-de-docentes-2024.csv        12268
actividad-de-docentes-2025.csv        12262
datos_docentes_2022.csv               10905
datos_docentes_2021.csv               10386
datos_docentes_2020.csv                9928
datos_docentes_2019.csv                9610
Name: count, dtype: int64

In [22]:
variacion = dup.groupby(["Id persona", "Año lectivo"])[["Sexo", "Departamento", "Subsistema", "acciones"]].nunique()

In [23]:
variacion.head()

                        Sexo  Departamento  Subsistema  acciones
Id persona Año lectivo
1000117    2023            1             2           2         1
           2024            1             1           2         1
           2025            1             2           2         1
10044      2023            1             1           2         1
           2024            1             1           2         1

In [24]:
(variacion > 1).sum()

Sexo                0
Departamento     4420
Subsistema      38934
acciones            1
dtype: int64

In [25]:
v_raros = variacion[(variacion["Subsistema"] == 1) | (variacion["acciones"] > 1)]
v_raros

                        Sexo  Departamento  Subsistema  acciones
Id persona Año lectivo
199850     2024            1             1           1         2

In [26]:
df_d.duplicated(subset=["Id persona", "Año lectivo", "Subsistema"]).sum()

np.int64(1)

**Aclaración de nueva hipótesis**

A partir de lo anterior, podemos concluir de que la hipótesis "una fila por docente y año" no es cierta, pues 
nos dió 39.031 repeticiones. Por ende, descartamos esta idea.

Sin embargo, la idea de "cada fila es un docente, en un año, en un subsistema" resistió a la prueba anterior.
Solamente ocurrió una repetición entre los años 2019 al 2025, por lo que momentáneamente es la mejor hipótesis que tenemos.

In [27]:
df_d[df_d.duplicated(subset=["Id persona", "Año lectivo", "Subsistema"], keep=False)]

,Id persona,Sexo,Rol,Departamento,Subsistema,Año lectivo,Cantidad de días ingreso a CREA,Cantidad de días de ingreso a Biblioteca,Cantidad de préstamos en biblioteca,archivo_origen,comentarios,acciones
1,199850,Masculino,Docente,Montevideo,DGETP,2024,0,0,0,actividad-de-docentes-2024.csv,0.0,0.0
2284,199850,Masculino,Docente,Montevideo,DGETP,2024,136,2,0,actividad-de-docentes-2024.csv,24.0,1478.0

In [28]:
nulos_docentes = df_d.isna()

print(f"La cantidad de nulos por columna es:\n{nulos_docentes.sum()}\n ---------")
print(f"La proporción (%) de nulos por columna es de: \n{nulos_docentes.mean()}\n ----------")

La cantidad de nulos por columna es:
Id persona                                  0
Sexo                                        0
Rol                                         0
Departamento                                0
Subsistema                                  0
Año lectivo                                 0
Cantidad de días ingreso a CREA             0
Cantidad de días de ingreso a Biblioteca    0
Cantidad de préstamos en biblioteca         0
archivo_origen                              0
comentarios                                 0
acciones                                    0
dtype: int64
 ---------
La proporción (%) de nulos por columna es de:
Id persona                                  0.0
Sexo                                        0.0
Rol                                         0.0
Departamento                                0.0
Subsistema                                  0.0
Año lectivo                                 0.0
Cantidad de días ingreso a CREA             0.0
Cantidad de días de ingreso a Biblioteca    0.0
Cantidad de préstamos en biblioteca         0.0
archivo_origen                              0.0
comentarios                                 0.0
acciones                                    0.0
dtype: float64
 ----------

**Aclaración sobre los valores nulos**

En este caso, hay que tener mucho cuidado, el código anterior con .isna() arrojó de que no hay valores faltantes **codificados como NaN, así que si los faltantes están codificados como strings "Sin dato" o "Valor faltante" no serán contabilizados**. Dicho esto, se procederá a verificar cuántos valores "Sin dato" existen por cada columna.

In [29]:
for col in df_d.columns:
    cantidad = (df_d[col] == "Sin Dato").sum()
    print(col, cantidad)

Id persona 0
Sexo 480
Rol 0
Departamento 39
Subsistema 0
Año lectivo 0
Cantidad de días ingreso a CREA 0
Cantidad de días de ingreso a Biblioteca 0
Cantidad de préstamos en biblioteca 0
archivo_origen 0
comentarios 0
acciones 0

In [30]:
df_d.nunique()

Id persona                                  74929
Sexo                                            3
Rol                                             1
Departamento                                   20
Subsistema                                      3
Año lectivo                                     7
Cantidad de días ingreso a CREA               327
Cantidad de días de ingreso a Biblioteca      223
Cantidad de préstamos en biblioteca           141
archivo_origen                                  7
comentarios                                  2362
acciones                                     7551
dtype: int64

In [31]:
verificar_columnas = ["Sexo", "Rol", "Departamento", "Subsistema", "Año lectivo", "archivo_origen"]

for ncol in verificar_columnas:
    ncantidad = df_d[ncol].value_counts(dropna=False)
    print(f"\n{ncantidad}\n ---------")

Sexo
Femenino     286437
Masculino     92236
Sin Dato        480
Name: count, dtype: int64
 ---------

Rol
Docente    379153
Name: count, dtype: int64
 ---------

Departamento
Montevideo        109581
Canelones          61600
Maldonado          20495
Salto              17980
Colonia            17806
Rivera             16286
Paysandu           16201
San Jose           13800
Tacuarembo         13613
Cerro Largo        12635
Soriano            12135
Artigas            11975
Rocha              10524
Florida             9781
Rio Negro           8279
Durazno             8230
Lavalleja           7536
Treinta Y Tres      7169
Flores              3488
Sin Dato              39
Name: count, dtype: int64
 ---------

Subsistema
DGES     148974
DGEIP    137682
DGETP     92497
Name: count, dtype: int64
 ---------

Año lectivo
2023    59534
2025    56074
2024    55165
2022    54495
2021    52393
2019    51370
2020    50122
Name: count, dtype: int64
 ---------

archivo_origen
docentes_datos_abiertos_agesic.csv    59534
actividad-de-docentes-2025.csv        56074
actividad-de-docentes-2024.csv        55165
datos_docentes_2022.csv               54495
datos_docentes_2021.csv               52393
datos_docentes_2019.csv               51370
datos_docentes_2020.csv               50122
Name: count, dtype: int64
 ---------

### Verificación de la columna `Sexo`

Verificaremos esta columna, la cual tiene 480 "Sin Dato"

In [32]:
df_sin_sexo = df_d[df_d["Sexo"] == "Sin Dato"].copy()
df_sin_sexo.head(480)

,Id persona,Sexo,Rol,Departamento,Subsistema,Año lectivo,Cantidad de días ingreso a CREA,Cantidad de días de ingreso a Biblioteca,Cantidad de préstamos en biblioteca,archivo_origen,comentarios,acciones
54607,2078074,Sin Dato,Docente,Canelones,DGES,2024,13,0,0,actividad-de-docentes-2024.csv,8.0,58.0
111547,18772,Sin Dato,Docente,Colonia,DGES,2019,80,0,0,datos_docentes_2019.csv,24.0,222.0
112665,25732,Sin Dato,Docente,Paysandu,DGES,2019,1,0,0,datos_docentes_2019.csv,0.0,4.0
114515,78758,Sin Dato,Docente,Tacuarembo,DGES,2019,0,0,0,datos_docentes_2019.csv,0.0,0.0
118019,192944,Sin Dato,Docente,Colonia,DGES,2019,0,0,0,datos_docentes_2019.csv,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
374910,1136520,Sin Dato,Docente,Rocha,DGES,2023,4,1,0,docentes_datos_abiertos_agesic.csv,0.0,6.0
377114,1394511,Sin Dato,Docente,Soriano,DGES,2023,49,0,0,docentes_datos_abiertos_agesic.csv,0.0,103.0
379062,2032575,Sin Dato,Docente,Salto,DGES,2023,0,0,0,docentes_datos_abiertos_agesic.csv,0.0,0.0
379063,2032575,Sin Dato,Docente,Salto,DGETP,2023,0,0,0,docentes_datos_abiertos_agesic.csv,0.0,0.0
379119,2038151,Sin Dato,Docente,Rocha,DGETP,2023,18,9,10,docentes_datos_abiertos_agesic.csv,0.0,128.0

### Tratamiento de los "Sin Dato" en `Sexo`

**Observación**
- `isna()` da 0 nulos, pero `Sexo` tiene 480 filas con el texto "Sin Dato" (0,13% de las 379.153 filas).
- Esas filas corresponden a 465 docentes. De ellos, 62 tienen el sexo registrado en otras filas y 403 no lo tienen en ninguna.
**Decisión**
1. Para los 62 docentes con sexo conocido en otras filas: se completó `Sexo` con ese valor en 67 filas. Antes se verificó que cada uno de esos 62 docentes tiene un único sexo entre sus filas conocidas.
2. Para los 403 docentes sin sexo conocido en ninguna fila (413 filas): se conservan con "Sin Dato" como categoría y se excluyen solo en los análisis que usen `Sexo`.
3. No se imputa con proporción 50/50 ni con la proporción observada.

**Justificación**
- Completar desde otras filas del mismo docente no inventa información: usa un dato registrado para esa misma persona.
- Imputar con una proporción inventaría un dato que el origen no registra. Además, supondría que los faltantes se reparten igual que los datos conocidos, algo que no verificamos (ver hipótesis pendientes).
- Borrar las filas habría eliminado 403 docentes del dataset (74.929 → 74.526) y descartado información válida de otras columnas (departamento, subsistema, uso de plataformas) en análisis que no dependen del sexo.
- Mantener "Sin Dato" permite medir cuánto afecta el faltante a cada análisis.

**Efecto comprobado**
- Filas "Sin Dato" en `Sexo`: 480 → 413.
- Docentes con "Sin Dato": 465 → 403.
- Filas totales: 379.153 (sin cambio). Docentes totales: 74.929 (sin cambio).
- Nulos en `Sexo`: 0.

**Limitación**
- Todo análisis por sexo cubrirá 74.526 docentes, no los 74.929 del dataset.

**Hipótesis pendientes (sin verificar)**
- Los docentes con "Sin Dato" aparecen pocas veces (1,4 filas contra 5 de promedio). No sabemos si es por ingreso reciente, por un problema de registro u otra causa.
- Los faltantes podrían concentrarse en ciertos departamentos o subsistemas, y no estar repartidos como los datos conocidos. Se puede comprobar con una tabla de `Departamento` y `Subsistema` para los 403 docentes frente al resto.
- Un docente (ID 530768) figura con "Femenino" en seis años y con "Sin Dato" solo en 2023. Podría ser un problema de registro de un año, pero con un solo caso no se puede afirmar. Se puede consultar a Ceibal.

In [39]:
ids_sin_sexo = df_sin_sexo["Id persona"].unique()
mask = df_d["Id persona"].isin(ids_sin_sexo)
filas_de_esos = df_d[mask].copy()
filas_de_esos["Sexo"].value_counts()

Sexo
Sin Dato     480
Femenino     122
Masculino     62
Name: count, dtype: int64

In [40]:
conocido = filas_de_esos[filas_de_esos["Sexo"] != "Sin Dato"]
conocido["Id persona"].nunique()

62

In [41]:
docentes_antes = df_d["Id persona"].nunique()

df_sin_borrar = df_d[df_d["Sexo"] != "Sin Dato"]
docentes_despues = df_sin_borrar["Id persona"].nunique()

print(docentes_antes, docentes_despues, docentes_antes - docentes_despues)

74929 74526 403

In [46]:
consistencia = conocido.groupby("Id persona")["Sexo"].nunique()
consistencia.value_counts()

Sexo
1    62
Name: count, dtype: int64

In [56]:
# Ahora vamos a crear una tabla de consulta para ver dichas 62 filas
# No es necesario hacerlo, pero metodológicamente me parece correcto.

una_por_docente = conocido.drop_duplicates("Id persona")
tabla_docentes = una_por_docente.set_index("Id persona")["Sexo"]
len(tabla_docentes)

62

In [57]:
mascara = (df_limpio["Sexo"] == "Sin Dato") & (df_limpio["Id persona"].isin(tabla_docentes.index))
mascara.sum()

np.int64(67)

In [58]:
id_ejemplo = tabla_docentes.index[0]
df_d[df_d["Id persona"] == id_ejemplo][["Id persona", "Año lectivo", "Subsistema", "Sexo"]]

       Id persona  Año lectivo Subsistema      Sexo
290        530768         2024      DGETP  Femenino
55394      530768         2025      DGETP  Femenino
130137     530768         2019       DGES  Femenino
130138     530768         2019      DGETP  Femenino
180639     530768         2020      DGETP  Femenino
180640     530768         2020       DGES  Femenino
231686     530768         2021       DGES  Femenino
231687     530768         2021      DGETP  Femenino
284973     530768         2022       DGES  Femenino
284974     530768         2022      DGETP  Femenino
341272     530768         2023      DGETP  Sin Dato
341273     530768         2023       DGES  Sin Dato

In [59]:
es_sin_dato = df_limpio["Sexo"] == "Sin Dato"
esta_en_tabla = df_limpio["Id persona"].isin(tabla_docentes.index)
mascara = es_sin_dato & esta_en_tabla
mascara.sum()

np.int64(67)

In [62]:
df_limpio.loc[mascara, "Sexo"] = df_limpio.loc[mascara, "Id persona"].map(tabla_docentes)

In [72]:
# Ahora conviene comprobar el estado del nuevo df, de la limpieza y de la consolidación de los cambios

verificacion_m1 = (df_limpio["Sexo"] == "Sin Dato").sum()
verificacion_m2 = df_limpio.loc[df_limpio["Sexo"] == "Sin Dato", "Id persona"].nunique()
verificacion_m3 = print(f"El número de filas {len(df_limpio)} + y + docentes {df_limpio["Id persona"].nunique()}")
verificacion_m4 = df_limpio["Sexo"].isna().sum()

print(f"Filas que siguen en 'Sin Dato': {verificacion_m1}")
print(f"Docentes que siguen sin sexo conocido: {verificacion_m2}")
verificacion_m3
print(verificacion_m4)

El número de filas 379153 + y + docentes 74929
Filas que siguen en 'Sin Dato': 413
Docentes que siguen sin sexo conocido: 403
0